export const data = [
  {
    nombres: "sandra",
    apellidos: "uribe",
    correo: "uri.30@gmail.com",
    edad: 30,
    salario: 15,
    cargo: "coordinadora",
  },
  {
    nombres: "andres",
    apellidos: "castaño",
    correo: "casta.30@gmail.com",
    edad: 24,
    salario: 61,
    cargo: "cajero",
  },
  {
    nombres: "camilo",
    apellidos: "ramirez",
    correo: "rami.30@gmail.com",
    edad: 31,
    salario: 16,
    cargo: "coordinador",
  },
  {
    nombres: "mariana",
    apellidos: "trujillo",
    correo: "tru.30@gmail.com",
    edad: 36,
    salario: 14,
    cargo: "zapatera",
  },
  {
    nombres: "lady",
    apellidos: "cano",
    correo: "cano.30@gmail.com",
    edad: 34,
    salario: 14,
    cargo: "creditos",
  },
  {
    nombres: "sol",
    apellidos: "casas",
    correo: "casas.30@gmail.com",
    edad: 35,
    salario: 155,
    cargo: "sombrillera",
  },
  {
    nombres: "alejandro",
    apellidos: "zapata",
    correo: "zap.30@gmail.com",
    edad: 36,
    salario: 19,
    cargo: "domiciliario",
  },
  {
    nombres: "bernal",
    apellidos: "lopez",
    correo: "lop.30@gmail.com",
    edad: 22,
    salario: 22,
    cargo: "carpintero",
  },
  {
    nombres: "valeria",
    apellidos: "tabares",
    correo: "tab.30@gmail.com",
    edad: 18,
    salario: 18,
    cargo: "farmaceutica",
  },
  {
    nombres: "cecilia",
    apellidos: "villa",
    correo: "vil.30@gmail.com",
    edad: 69,
    salario: 66,
    cargo: "coordinadora",
  },
  {
    nombres: "camila",
    apellidos: "zapata",
    correo: "zapata.30@gmail.com",
    edad: 54,
    salario: 23,
    cargo: "maquilladora",
  },
  {
    nombres: "estefania",
    apellidos: "ocampo",
    correo: "ocam.30@gmail.com",
    edad: 32,
    salario: 24,
    cargo: "manicurista",
  },
  {
    nombres: "jaqueline",
    apellidos: "morales",
    correo: "mora.30@gmail.com",
    edad: 64,
    salario: 82,
    cargo: "confeccionista",
  },
  {
    nombres: "sofia",
    apellidos: "guerra",
    correo: "guerr.30@gmail.com",
    edad: 45,
    salario: 33,
    cargo: "administradora",
  },
  {
    nombres: "tania",
    apellidos: "yate",
    correo: "yate.30@gmail.com",
    edad: 23,
    salario: 25,
    cargo: "barbera",
  },
];
